spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  flyway:
    locations: classpath:db/migration
    placeholder-replacement: false
    enabled: true
  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: none