version: '3.7'
services:
  user-service:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongo-database
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:mongo@mongo-database:27017/user_service"
      SPRING_DATA_MONGODB_DATABASE: user_service
    ports:
      - "8082:8082"

  mongo-database:
    image: mongo:4.2.5-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: KaonNa2
      MONGO_INITDB_DATABASE: user_service
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"